name: dashboard_template_dribbble
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^1.0.0
  intl: ^0.20.2
  provider: ^6.1.5
  video_player: ^2.10.0
  http: ^1.4.0
  shared_preferences: ^2.5.3
  easy_localization: ^3.0.5
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
